### ISSUE TITLE
How to sign a request with a json payload?

### ISSUE THREAD

**Issue by MachinesAreUs** [lexmag/oauther#7]
I see that the signing assumes the parameters for the endpoint are a list of tuples and two values each, but when you need to send a json document as the payload this doesn´t work. How could you do that with `oauther`? Is this a missing use case?

**Comment by lexmag** [comment]
Hey @MachinesAreUs, is there any public API you trying to reach this way?

**Comment by WildYorkies** [comment]
I am having the same exact issue. I've tried all variations of your example and nothing works. Pulling my hair out :laughing: 

I need to
- Make a post request
- Send a json payload like `{:ok, payload} = Poison.encode %{start: %{from: from, to: to}}`
- Sign my response with oauth1
- include query parameters on the end of my URL

Python makes this easy because the request format is like
```python
client.post(url=url, headers=postheader, data=json.dumps(body), auth=oauth, params=params)
```

It clearly has a field for url, header (where the content type goes), data (where the json goes), auth (where the oauth1 sig goes), and params (where the url query parameters go).

@lexmag your example is confusing to me because it seems to roll the oauth, header, and params all into one thing.

This is probably more of an issue with HTTPoison, but could you show an example of delivering a json payload with a POST with HTTPoison and Oauther?

**Comment by lexmag** [comment]
Hey @WildYorkies, sad to know that it was not pleasant experience for you. 😢
I really want to improve it, is it public API that you're trying to access?
According RFC, if you you have non-"application/x-www-form-urlencoded" body, it should not be used in signature generation.

**Comment by WildYorkies** [comment]
@lexmag I'm sure the unpleasantness is from my lack of expertise working with clients :)

The API is only semi-public. But what I am trying to do is essentially the same as POSTing a tweet with the twitter API.

Authentication is one-legged oauth1. 

Does that help?

**Comment by lexmag** [comment]
> But what I am trying to do is essentially the same as POSTing a tweet with the twitter API.

@WildYorkies I have just tried to update user's settings (POSTing a tweet works in the exactly the same way), it worked flawlessly: 

```elixir
credentials = OAuther.credentials(consumer_key: "", consumer_secret: "", token: "", token_secret: "")
url = "https://api.twitter.com/1.1/account/settings.json"
params = [{"lang", "en"}]
all_params = OAuther.sign("post", url, params, credentials)
{header, req_params} = OAuther.header(all_params)
req_headers = [header, {"content-type", "application/x-www-form-urlencoded; charset=UTF-8"}]
req_body = URI.encode_query(req_params)
{:ok, 200, _resp_headers, ref} = :hackney.post(url, req_headers, req_body)
{:ok, resp_body} = :hackney.body(ref)
```

Hard to say how it would look in your case without looking at API you're working with, but I assume the following should work:

```elixir
credentials = OAuther.credentials(...)
url = ...
params = ...
all_params = OAuther.sign("post", url, params, credentials)
{header, req_params} = OAuther.header(all_params)
req_headers = [header, {"content-type", "application/json; charset=UTF-8"}]
encoded_req_params = URI.encode_query(req_params)
req_body = Poison.encode!(..)
{:ok, 200, _resp_headers, ref} = :hackney.post([url, "?", encoded_req_params], req_headers, req_body)
{:ok, resp_body} = :hackney.body(ref)
```

**Comment by WildYorkies** [comment]
@lexmag Thank you for that example. I think I'm confusing a json payload with query params that go at the end of the url. It's confusing because both of them _look_ like json.

In any case, there's a lot going on in your examples that I'll need to unpack. Thanks, though!

P.S. - Why do you use hackney instead of HTTPoison? I was under the impression that HTTPoison was the more popular library. The difference between these two library's APIs can be confusing too.

**Comment by lexmag** [comment]
@WildYorkies I use hackney because of the reason that HTTPoison is just a wrapper over hackney, I personally don't see any benefits of using it. :bowtie:

I'm closing this issue as it seems there is no problem with JSON payload sending, but fell free to reopen if it still doesn't work for you.
